### ISSUE TITLE
Battery Charger & Wardrobe Locations

### ISSUE THREAD

**Issue by Wemmy0** [x753/Lethal-Company-More-Suits#11]
With enough suits, it becomes impossible to use the battery charger without getting stuck inside the wardrobe and dying.
I can't also seem to move the wardrobe by pressing `B`

**Comment by x753** [comment]
I'll rely on others to implement their preferred method of fixing this, like this: https://thunderstore.io/c/lethal-company/p/Verity/TooManySuits/
