### ISSUE TITLE
Friends have the same exacts folder yet the suits are all orange most of the time

### ISSUE THREAD

**Issue by aazza94** [x753/Lethal-Company-More-Suits#15]
We are all using the exact same moresuits folder for our suits, as I made it and shared it. But when they boot into my lobby, half of the time (if not most of the time) they only see orange suits.

I have the rail page mod installed as well, but that is it.

Can you please shed some light on why this might be happening if you can? or see if it might be bugged? We would all love to play with custom suits but it isnt consistent at the moment.

Love your work though dude, if you could email me at aaronhoustonwkw@gmail.com witha  potential fix, ill be greatful

**Comment by UnknownDev37** [comment]
Same issues, but I do have a handfull of mods, works at the start but then reloading the save makes them all orange like you said of other players.
Im on MoreCompany.
Other then TooManySuits, do you have LC API installed too or just the minumum?

**Comment by aazza94** [comment]
I do have more company installed, but it was doing this without more
company. I don't have the API installed either mate

**Comment by x753** [comment]
I believe as of the update you need a new save in order for things to sync properly.
