### ISSUE TITLE
Add suits to the store and not on rack

### ISSUE THREAD

**Issue by labmonjos** [x753/Lethal-Company-More-Suits#17]
Hello,

I am using this mod (1.3.3 on LC v45) and I added the PRICE tag to the suits I want priced. However, upon new game, they don't appear on the rack (expected) but exiting the save and rejoining puts those suits on the rack as if I got them for free (unexpected). The Terminal shows I can buy the suits before and after the free suits appear.

How can I keep these suits behind the credit currency paywall like the vanilla suits?

Thanks,

**Comment by x753** [comment]
Try making a new save and things should work as intended.

**Comment by labmonjos** [comment]
> Try making a new save and things should work as intended.

I have been trying this in new saves. The issue is it works on first join of a brand new save, but leaving the save and opening the same save puts all the suits on the rack.

Thanks,

**Comment by SuicidalBomb** [comment]
> > Try making a new save and things should work as intended.
> 
> I have been trying this in new saves. The issue is it works on first join of a brand new save, but leaving the save and opening the same save puts all the suits on the rack.
> 
> Thanks,

This is happening to me currently, All my suits are buyable, but upon exiting to menu and loading they are given to me for free.

**Comment by x753** [comment]
I've fixed this in the latest version (v1.4.0)
