### ISSUE TITLE
No Suits in Multiplayer | MoreSuits1.1.0

### ISSUE THREAD

**Issue by UnknownDev37** [x753/Lethal-Company-More-Suits#2]
Using More Company for multiplyer and MikeTweaks. Only Host can see Suits.

**Comment by UnknownDev37** [comment]
![Capture](https://github.com/x753/Lethal-Company-More-Suits/assets/17447099/8c3de2fb-c731-436f-98dc-2b8b4e938b97)

**Comment by UnknownDev37** [comment]
We found them merged into one on company.
![Capture2](https://github.com/x753/Lethal-Company-More-Suits/assets/17447099/3c80fd95-20f7-4efc-959e-e0999031323c)

**Comment by UnknownDev37** [comment]
The suit(bugged into one) is outside the ship.
![Capture3](https://github.com/x753/Lethal-Company-More-Suits/assets/17447099/901cf024-0a31-4cf3-a7fb-8067a10c2cfa)

**Comment by x753** [comment]
It would seem that MoreCompany causes desync with ship objects such as suits, so my suit mod isn't working with it. For the time being, I recommend using BiggerLobby for compatibility. I personally use this version:
https://thunderstore.io/c/lethal-company/p/bizzlemip/BiggerLobby/v/2.0.4/
