### ISSUE TITLE
Custom suits causing infinite rack

### ISSUE THREAD

**Issue by Lottita** [x753/Lethal-Company-More-Suits#23]
Hello! I'm making around 10 custom suits for me and my friends using your mod. I was having no issues, but after 1.4.0, the suit rack has infinite orange suits on top of my fully functional custom suits, expanding towards the terminal and clipping out of the ship. I can provide pictures of everything needed.

I tried switching the suit stacking to false, and that didn't fix the issue. I also tried removing the suits one by one to see if there was one specific one causing an issue, and to no avail.

**Comment by x753** [comment]
Are you using a mod that unlocks all suits by default? The game adds up to 100 dummy suits to protect syncing when people add files. If you want to fix this, change the max suits config option to however many suits you have.

**Comment by x753** [comment]
This should be fixed if you update to v1.4.1
