### ISSUE TITLE
unclear advanced features

### ISSUE THREAD

**Issue by billydotexe** [x753/Lethal-Company-More-Suits#24]
the advanced folder only contains example for emission maps, the advanced section in the readme has a link to the unity docs for "a list of supported features" but the docs and the keyword to add in the json are kinda unclear. I've tried for quite some time to create a suit with a metallic map and I'm stuck trying keywords.

I even created the material in unity with the lit shader (the one liked) and I was able to obtain the result I'm trying to achieve but then it won't work in game
![image](https://github.com/x753/Lethal-Company-More-Suits/assets/33807897/fc905345-9bef-4f7d-b956-9a93dc085afa)

this is what I added in the json. is there something I'm missing or is the effect unachievable in game?
``` json
"_METALLICSPECGLOSSMAP": "KEYWORD",
"_MetallicGlossColorMap" : "White_pijama_metallic.png",
"_Smoothness" : 1.0
```

**Comment by x753** [comment]
You're using the wrong version of Unity. The shader you should be using is HDRP/Lit, not URP/Lit.

If you want to figure it out you'll probably have to rip the materials from the game with Asset Ripper and look at the unserialized asset data, use the same version of Unity with an HDRP setup, and do a lot of experimentation. Unity Explorer can also be used to modify materials at runtime for experimenting.
