### ISSUE TITLE
Can't buy suits that start with a capital letter

### ISSUE THREAD

**Issue by VirtualFishbowl** [x753/Lethal-Company-More-Suits#30]
Suits will appear in the store as expected, but I'm unable to purchase them. (There was no action supplied with the word) shows in terminal. When I renamed files to remove capital letter from the front, the bug was fixed.

**Comment by x753** [comment]
The single buyable suit that comes with the mod starts with a capital letter (Glow.png) and works for me. Are you using capital letters when trying to buy it?
