### ISSUE TITLE
New Version 47 update creates issues with suit mods.

### ISSUE THREAD

**Issue by BobtheBromosapien** [x753/Lethal-Company-More-Suits#35]
After Update 47, I have found that More Suits + various suit mods are not behaving correctly (since suit mods rely on More Suits). 

For example, when loading any existing saves, all modded suits will appear as a full rack of default suits. 
Other times players will only see the modded suits they are wearing themselves and the modded suits everyone else is wearing appears default. 

The mod does function completely fine when starting with a fresh lobby with no loaded saves. Essentially a totally fresh lobby but as soon as you load that fresh save, the suits are broken again.
Just figured I would provide a more detailed heads up on some of the issues Version 47 has created.

**Comment by x753** [comment]
I can't recreate this bug on my end. Make sure everyone is playing on the same version and has the same files.

**Comment by Doc94** [comment]
i have a similar issue, if update to v48 and use a previous save the lobby loaded not show the suits.
![image](https://github.com/x753/Lethal-Company-More-Suits/assets/3602279/38730d93-23cf-4d2a-af32-a1a2919ee36e)
 but if i use a new save game this issue not happen.
[LogOutput.log](https://github.com/x753/Lethal-Company-More-Suits/files/13873216/LogOutput.log)

**Comment by BobtheBromosapien** [comment]
I solved the issue for me personally. This mod is totally incompatible with "Additional Suits" by AlexCodesGames
If both .dll files are present in Plugins, it causes both to break. By removing Additional Suits .dll file and then moving all the suit images into the More Suits folder, More Suits then behaves as normal and uses the suits from Additional Suits.

But at present, you cannot use both of these suit mods together, or at least on my end. It causes all of the issues listed in my first comment.

**Comment by Doc94** [comment]
For my case i dont have the Additional Suits. but i finally start a new save and this not happen.... the only issue is when restart the lobby and all suits show orange...

**Comment by BobtheBromosapien** [comment]
Okay after further testing, it still can occur just not as often. We had someone crash while playing on a day 10 save. After closing the lobby and rebooting, the suits did not work for anyone but the host. Everyone has the suits downloaded and installed correctly. They copied my filed directly, I provided my entire BepInEx folder and had them move it into the Lethal Company folder and accept all "replace" prompts.

Something with the mod needs tweaked for sure. In order to test, you will need another player. You will not be able to replicate it alone more than likely.

I would also keep this thread open, because others are experiencing it too.
