### ISSUE TITLE
Making new modpack

### ISSUE THREAD

**Issue by MetaOrgins** [x753/Lethal-Company-More-Suits#38]
I made a new mod pack but when I downloaded it from thunderstore it threw everything in one folder and it didn't work even though the zip I uploaded had folders

**Comment by x753** [comment]
The mod loader dissolves folders unless they're in specifically named folders. In your zip, add folders called BepInEx/Plugins and put your suits folder in there, so it looks like:
MyPack.zip/BepInEx/plugins/MoreSuits/suit.png
