### ISSUE TITLE
Some suits dont show up !lessSuits

### ISSUE THREAD

**Issue by ggMatze** [x753/Lethal-Company-More-Suits#39]
some suits like Mario.png dont show up if i dont set ignore less suits to true,
even if there is no lesssuits file containing those suits.

**Comment by x753** [comment]
Perhaps someone set Mario.png not to load with the config file?

**Comment by ggMatze** [comment]
i checked all files, in the config its not disabled. And its not just mario, not sure what the problem is there.

**Comment by x753** [comment]
I'm not sure what it could be then. I recommend adding mods one by one until you find out which one broke it.

**Comment by ggMatze** [comment]
i found the mod causing itViViKoCosmetics(ViViKoCosmetics), but the !lessSuits.txt is empty, no files specified
