### ISSUE TITLE
Suits appear outside/ not at all

### ISSUE THREAD

**Issue by Withergaming101** [x753/Lethal-Company-More-Suits#41]
While it is not your mod specifically, it is a suit mod using more-suits, and from what I can tell, the problem stems from this. Please correct me if I am wrong.

I have been using 'Lethal Fortress 2' suits (TF2 characters as suits), and I can see all suits just fine, but my friend does not see them. Infact, the suit-rack is not even on the ship. We managed to find one of the 9 added suits outside the ship, middle of nowhere on the map, where they could change and use that suit. We have yet to find more than one suit at a time when playing.

**Comment by Thijs-van-Rixoort** [comment]
I have the same problem. The suit rack is empty or just not in the ship at all.

**Comment by Hu-Myo** [comment]
I'm not involved with this mod, but I know why this is happening
When uploading the mod, the moresuits folder in the zip file should be inside the plugins folder, but it's outside of it
This is an issue with the way the mod is organized, so for the next update, you should create a random folder (any name will do) and put moresuits in it and it should work

For now, the workaround is to manually go into the plugins folder, find all the images (icon.png) and !less-suit.txt files in this mod's folder, create a moresuits folder, and put it inside.
