### ISSUE TITLE
High Ram Usage

### ISSUE THREAD

**Issue by DreiPixel** [x753/Lethal-Company-More-Suits#42]
This mod seems to cause high ram usage of Lethal Company.
just by activating this mod without adding any suits Lethal's ram usage goes up by about 2-3 gb.
with over 100 suits added the highest Ram usage i observed in Lethal was 11gb just because of suits.

**Comment by x753** [comment]
I don't believe there's any simple solution other than compressing them and only using the suits you plan on using.
