### ISSUE TITLE
Players models equipping with different suits that selected

### ISSUE THREAD

**Issue by NavyEMC** [x753/Lethal-Company-More-Suits#43]
Sometimes when equipping a suit from the rack, the actual suit that makes it onto the player doesn't match the one selected. It is a different suit one or more spaces down the rack. Noticed during online multiplayer with both clients having the same mods installed. I have verified the correct suit name is indicated beneath the pointer when making selection.

**Comment by x753** [comment]
I haven't seen this issue myself, so I'm inclined to believe it's from another mod.
