### ISSUE TITLE
Suits are readable on CPU

### ISSUE THREAD

**Issue by DiFFoZ** [x753/Lethal-Company-More-Suits#46]
https://github.com/x753/Lethal-Company-More-Suits/blob/main/MoreSuits.cs#L156
Currently all suits are readable, so Unity creates 2 copy of texture and cause more RAM usage. To fix set `makeNoLongerReadable` to true to make it non readable.

**Comment by x753** [comment]
Seems like a simple fix, I addressed this in 1.4.2 which should be live now.
