### ISSUE TITLE
How to make better custom skins?

### ISSUE THREAD

**Issue by Evolv33** [x753/Lethal-Company-More-Suits#5]
The skins that were made by you are pretty-looking, but my skins are ass. How to make them as good as you did? I had an idea with Adobe 3d painter and character model, but i cant find it on the internet.

**Comment by Clark919** [comment]
Second this. I've made some okay skins by just altering the existing sprite sheets, but I can't figure out how to do wrapping textures for the curved parts of the model (visor, o2 cans). If there's an easier method than modifying textures using photoshop I'd love to know.

**Comment by ZaggLotus** [comment]
Hello, could you give a blueprint of the skin with an explanation of which part is responsible for what, otherwise my friends and I are trying to do and do not understand what is what and for this the colors do not converge.
Thank you in advance for the answer.

**Comment by funkmaster3000** [comment]
agreed. Been trying to get this going today and literally cannot find a clean screenshot of the way these textures wrap normally ingame, and you've provided a single blurry screenshot of the suits with no documentation. To be clear, yes I am asking for front and rear photos of the mario suit to compare against the texture image.

**Comment by x753** [comment]
The skins in the mod were mostly made in Substance Painter by Graelyth (twitter.com/graelyth).

GitHub Issues isn't a good place for sharing tutorials / files, here's a Discord link to where people have been discussing the creation of custom skins:
https://discord.com/invite/m7g6UB83Vr
https://discord.com/channels/1168655651455639582/1174822763186364486
