### ISSUE TITLE
[Feature Request] Rearrange the order of suits while keeping name

### ISSUE THREAD

**Issue by jacobmix** [x753/Lethal-Company-More-Suits#8]
Can you add it so we can change the order of suits without changing the name of the suits?
Example a json file that generates on launch that takes installed suits, and sorts them or auto adds new ones to the sort file, and we just can manually change?
Or if you add "0000_Default, 0001_blue, 0002_sky blue, 0003_red" to all suit names/pngs the underscore, and number before get's ignored? (Would be best if you didn't have to rename anything in the advanced folder too)

**Comment by x753** [comment]
The current version has sorting by texture paths alphabetically, so you manually renaming the files is probably your best bet here if you care about the order.

**Comment by jacobmix** [comment]
Would like to give or keep actual names for the items without worrying about the order.
But will live with renaming the files, and a number showing up with it.

**Comment by x753** [comment]
If you're crazy enough you can set up your folders like this:
BepInEx/plugins/myMod/01/moresuits/file1.png
BepInEx/plugins/myMod/02/moresuits/file2.png
BepInEx/plugins/myMod/03/moresuits/file3.png
